blank_issues_enabled: false
contact_links:
    - name: Ask Questions
      url: https://github.com/carbondigitalus/nekuta/issues/new/?category=question
      about: Create a support ticket to get help from developers. Please note that our discord community can be faster.
    - name: Facebook Group
      url: https://www.facebook.com/groups/nekutareactstores/
      about: The Nekuta Community, for general Nekuta questions or help.
